# Generated by Django 4.2.30 on 2026-06-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='things_to_carry',
            field=models.TextField(blank=True),
        ),
    ]
