# Generated by Django 4.2.30 on 2026-06-12 08:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('search_keywords', models.TextField(help_text='Search aliases like bangalore,bengaluru,blr')),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('hotel_type', models.CharField(choices=[('luxury', 'Luxury'), ('budget', 'Budget'), ('business', 'Business'), ('resort', 'Resort'), ('boutique', 'Boutique')], default='budget', max_length=20)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('villa', 'Villa'), ('homestay', 'Homestay'), ('apartment', 'Apartment')], default='hotel', max_length=20)),
                ('star_rating', models.DecimalField(decimal_places=1, default=3.5, max_digits=2)),
                ('user_rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('total_reviews', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('free_wifi', models.BooleanField(default=True)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=True)),
                ('restaurant', models.BooleanField(default=True)),
                ('airport_shuttle', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('breakfast_available', models.BooleanField(default=False)),
                ('couple_friendly', models.BooleanField(default=True)),
                ('free_cancellation', models.BooleanField(default=False)),
                ('pay_at_hotel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-star_rating', '-user_rating'],
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests', models.IntegerField(default=1)),
                ('rooms_count', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('executive', 'Executive Room')], max_length=30)),
                ('room_name', models.CharField(max_length=200)),
                ('max_guests', models.IntegerField(default=2)),
                ('total_rooms', models.IntegerField(default=10)),
                ('available_rooms', models.IntegerField(default=10)),
                ('room_size', models.IntegerField(default=200, help_text='Room size in sqft')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('extra_bed_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('refundable', models.BooleanField(default=False)),
                ('free_cancellation', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=True)),
                ('tv', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('room_image', models.URLField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_details', to='hotels.hotelbooking')),
            ],
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.room'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
