# Generated by Django 4.2.27 on 2025-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.CharField(blank=True, help_text='Supabase Auth user ID', max_length=255, null=True, unique=True),
        ),
    ]
