# Generated by Django 4.2.27 on 2025-12-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_supabase_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supabase_user_id',
        ),
    ]
