# Generated by Django 4.2.27 on 2025-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_supabase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(blank=True, editable=False, help_text='Supabase Auth user ID (UUID)', null=True, unique=True),
        ),
    ]
