# Generated by Django 4.2.30 on 2026-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_pricealert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.UniqueConstraint(
                fields=("flight_number", "departure_time"),
                name="unique_flight_departure",
            ),
        ),
    ]
