# Generated by Django 4.2.30 on 2026-06-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_hotelreview_rating_alter_packagereview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='packagereview',
            options={'ordering': ['-created_at']},
        ),
    ]
