from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
import re


def clean_markdown(text):

    if not text:
        return ""

    text = text.replace("₹", "Rs. ")

    # Remove markdown headings (#, ##, ###)
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)

    # Remove bold (**text**)
    text = text.replace("**", "")

    # Remove horizontal lines (---)
    text = text.replace("---", "")

    # Remove empty lines
    lines = []

    for line in text.split("\n"):

        line = line.strip()

        if line:
            lines.append(line)

    return "<br/>".join(lines)


def info_table(trip):
    data = [
        ["Destination", trip.destination.title()],
        ["Duration", f"{trip.days} Days"],
        ["Budget", f"Rs. {trip.budget}"],
        ["Estimated Cost", f"Rs. {trip.estimated_cost}"],
        ["Interests", trip.interests],
        ["Best Season", getattr(trip, "best_season", "Not Available")],
        ["Nearest Airport", getattr(trip, "nearest_airport", "Not Available")],
        ["Travel Style", getattr(trip, "travel_style", "Not Available")],
    ]

    table = Table(data, colWidths=[140, 320])

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0d6efd")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    return table


def generate_trip_pdf(trip):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=35,
        leftMargin=35,
        topMargin=40,
        bottomMargin=35,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.HexColor("#0d6efd")

    subtitle_style = styles["Heading2"]
    subtitle_style.alignment = TA_CENTER
    subtitle_style.textColor = colors.HexColor("#198754")

    heading = styles["Heading2"]
    heading.textColor = colors.HexColor("#0d6efd")

    body = styles["BodyText"]
    body.leading = 22

    story = []

    # -----------------------------------------------------------------
    # HEADER
    # -----------------------------------------------------------------

    story.append(Paragraph("TripEase", title_style))

    story.append(
        Paragraph(
            "Personalized AI Travel Itinerary",
            subtitle_style,
        )
    )

    story.append(Spacer(1, 25))

    # -----------------------------------------------------------------
    # SUMMARY TABLE
    # -----------------------------------------------------------------

    story.append(info_table(trip))

    story.append(Spacer(1, 25))

    # -----------------------------------------------------------------
    # ITINERARY
    # -----------------------------------------------------------------

    story.append(Paragraph("Day-wise Travel Plan", heading))

    story.append(Spacer(1, 10))

    story.append(Paragraph(clean_markdown(trip.generated_plan), body))

    story.append(Spacer(1, 25))

    # -----------------------------------------------------------------
    # AI INSIGHTS
    # -----------------------------------------------------------------

    story.append(Paragraph("Travel Intelligence", heading))

    story.append(
        Paragraph(
            f"""
            • Best time to visit:
            <b>{getattr(trip, 'best_season', 'Not Available')}</b>
            <br/><br/>

            • Nearest Airport:
            <b>{getattr(trip, 'nearest_airport', 'Not Available')}</b>
            <br/><br/>

            • Recommended Travel Style:
            <b>{getattr(trip, 'travel_style', 'Not Available')}</b>
            <br/><br/>

            • Estimated Trip Cost:
            <b>Rs. {trip.estimated_cost}</b>
            """,
            body,
        )
    )

    story.append(Spacer(1, 30))

    # -----------------------------------------------------------------
    # FOOTER
    # -----------------------------------------------------------------

    story.append(
        Paragraph(
            "<b>Generated by TripEase AI Planner</b>",
            subtitle_style,
        )
    )

    story.append(
        Paragraph(
            """
            This itinerary has been generated using the TripEase AI
            planning engine based on your travel preferences,
            destination, duration and budget.

            <br/><br/>

            We wish you a safe, memorable and enjoyable journey.

            <br/><br/>

            <font color="#777777">
            © TripEase • AI Powered Smart Travel Planner
            </font>
            """,
            body,
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer
