# Generated by Django 4.2.30 on 2026-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="travel_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
