# Generated by Django 4.2.30 on 2026-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
