# Generated by Django 4.2.30 on 2026-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_planner",
            "0002_tripplan_estimated_cost_tripplan_recommended_hotels_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tripplan",
            name="origin_city",
            field=models.CharField(default="Bengaluru", max_length=100),
        ),
    ]
